spring:
  cloud.gateway:
    server.webflux:
      httpclient:
        connect-timeout: 10000
        response-timeout: 5s
        pool:
          max-idle-time: 5s

  main:
    web-application-type: reactive
  data:
    redis:
      host: localhost
      port: 6544
      timeout: 500ms
      client-type: lettuce
      password: pass

# for example
jwt:
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxvKD2M7i9aEYmDI8fTYdBnZS9BsptPH9lW1Upn+0waI8S5F6am0at9CPfS10PAmzHcKSnwNI0+pUPEGClITE8gfZYTNegH/1UO1d5xSaorbICh9OhZGidDM4OzgW+coAddQgnjU5C9NG21ybsrNe9Dt5iU9CLDzmgQzl0xN2YDwrFyuzCCnIJvCdy3zLD9VrZ84S3H+bgzOGEbPawgBY6uvLKXu9GKrj85nVaq5XanEouPqBCD/k1uF+JLtz8ac3QX9wsxYONmEySuc4uoL/fcjOhI92HYVTT4YbK5Bu4+t/fvh1ga3hUhvPk4xyel/pXwyo/asntb1ETKeSwn8vNQIDAQAB"

server.port: 8081

security:
  public-endpoints:
    any-method:
      - /auth/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs.yaml
    get-only:
      - /question/*
      - /question/*/answer
      - /question/*/comments
      - /tags
